#!/usr/bin/env bash
set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo -e "${BLUE}[INFO] Starting Re:fox Native Messaging Host Installation...${NC}"

if [ ! -f /etc/arch-release ] && ! command -v pacman &>/dev/null; then
    echo -e "${YELLOW}[WARNING] This installer is optimized for Arch Linux and Arch-based distributions.${NC}"
fi

if [ "$EUID" -ne 0 ]; then
    echo -e "${YELLOW}[INFO] Root privileges required. Elevating with sudo...${NC}"
    exec sudo bash "$0" "$@"
fi

ACTUAL_USER="${SUDO_USER:-$USER}"
if [ "$ACTUAL_USER" = "root" ]; then
    echo -e "${YELLOW}[WARNING] Running as root without SUDO_USER. AUR building may require a regular user account.${NC}"
fi

install_aur_package() {
    local PKG="python-pywalfox"

    if pacman -Qi "$PKG" &>/dev/null; then
        echo -e "${GREEN}[INFO] $PKG is already installed.${NC}"
        return 0
    fi

    echo -e "${BLUE}[INFO] Installing $PKG from AUR...${NC}"

    if command -v paru &>/dev/null && [ "$ACTUAL_USER" != "root" ]; then
        sudo -u "$ACTUAL_USER" paru -S --noconfirm "$PKG"
    elif command -v yay &>/dev/null && [ "$ACTUAL_USER" != "root" ]; then
        sudo -u "$ACTUAL_USER" yay -S --noconfirm "$PKG"
    else
        echo -e "${BLUE}[INFO] No AUR helper found. Building $PKG with makepkg...${NC}"
        pacman -S --needed --noconfirm base-devel git python

        BUILD_DIR=$(mktemp -d /tmp/pywalfox-aur.XXXXXX)
        chown "$ACTUAL_USER" "$BUILD_DIR"

        sudo -u "$ACTUAL_USER" git clone https://aur.archlinux.org/python-pywalfox.git "$BUILD_DIR/python-pywalfox"
        cd "$BUILD_DIR/python-pywalfox"
        sudo -u "$ACTUAL_USER" makepkg -si --noconfirm
        cd - >/dev/null
        rm -rf "$BUILD_DIR"
    fi
}

install_aur_package

MAIN_SH_PATH=$(python3 -c "import pywalfox, os; print(os.path.join(os.path.dirname(pywalfox.__file__), 'bin', 'main.sh'))")

update_manifest() {
    local target_file="$1"
    mkdir -p "$(dirname "$target_file")"
    cat <<EOF > "$target_file"
{
  "name": "pywalfox",
  "description": "Automatically theme your browser using the colors generated by Pywal",
  "path": "$MAIN_SH_PATH",
  "type": "stdio",
  "allowed_extensions": [
    "pywalfox@frewacom.org",
    "re-fox@adior.org",
    "refox@adior.org"
  ]
}
EOF
    chmod 644 "$target_file"
}

MANIFEST_SYSTEM="/lib/mozilla/native-messaging-hosts/pywalfox.json"
update_manifest "$MANIFEST_SYSTEM"

USER_HOME=$(eval echo "~$ACTUAL_USER")
MANIFEST_USER="$USER_HOME/.mozilla/native-messaging-hosts/pywalfox.json"
update_manifest "$MANIFEST_USER"
chown "$ACTUAL_USER" "$MANIFEST_USER"

echo -e "${GREEN}[SUCCESS] Re:fox native messaging host installed successfully!${NC}"
echo -e "${GREEN}[SUCCESS] Supported browsers: Firefox, LibreWolf, Floorp, Mercury, Zen.${NC}"
